spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/mydb?createDatabaseIfNotExist=true
    username: ${DB_ROOT_NAME:root}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}
    change-log: ${LIQUIBASE_CLASSPATH:classpath:db/changelog/db.changelog-${ACTIVE_PROFILE:master}.yaml}

server:
  port: 8099