spring:
  cache:
    type: redis
    redis:
      time-to-live: 600000
  redis:
    host: localhost
    port: 6379
logging:
  level:
    root: INFO
    redis.clients: TRACE
#    org.springframework.data: TRACE

redis:
  hostname: localhost
  port: 6379
  username:
  password: